#!/bin/bash
set -e # Exit on any child process error

echo "Deploying: awsudo/awsudo"
cat package.json | mustache - Docker.template > Dockerfile

VERSION=`node -p "require('./package').version"`

echo "Logging in"
docker login
echo "Building..."
docker build . -t awsudo/awsudo:latest -t awsudo/awsudo:v${VERSION}
echo "Push awsudo/awsudo:v${VERSION}"
docker push awsudo/awsudo:v${VERSION}
echo "Push awsudo/awsudo:latest"
docker push awsudo/awsudo:latest
echo "All done!"